global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['grafana-node-exporter-1-1-2:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['grafana-cadvisor-0-33-0:8080']

