tls:
    options:
        default:
            minVersion: VersionTLS12
            cipherSuites:
             - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
             - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
             - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
             - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
             - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
             - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        tlsv13only:
            minVersion: VersionTLS13

http:
    middlewares:
        secHeaders:
            headers:
                browserXssFilter: true
                contentTypeNosniff: true
                frameDeny: true
                sslRedirect: true
                #HSTS Configuration
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
                customFrameOptionsValue: "SAMEORIGIN"

